import { ADMIN_WALLET_ADDRESSES, SHARES_PER_PROPERTY, ZERO_WALLET, seedWallets } from "../config/constants.mjs";
import { randomHex, seededVerifiedWallets, sha256Hex } from "../utils/values.mjs";

export const baseDb = () => {
  const submittedAt = "2026-01-15T09:00:00.000Z";
  const approvedAt = "2026-01-16T10:30:00.000Z";
  const propertyOneHash = sha256Hex("Mountain View Villa legal document bundle");
  const propertyTwoHash = sha256Hex("Norzin Lam commercial office legal document bundle");
  const propertyThreeHash = sha256Hex("Taba prime land parcel legal document bundle");

  return {
    version: 2,
    nextTokenId: 1004,
    verifiedWallets: seededVerifiedWallets(),
    users: [
      {
        holderDid: "did:key:demo-seller",
        idNumberDisplay: "SELLER-001",
        walletAddress: seedWallets.sellerA,
        role: "user",
        sessionToken: "demo-seller-session",
        ndiProofThreadId: "seed-seller-thread",
        ndiVerifiedAt: approvedAt,
        createdAt: submittedAt,
        suspended: false,
      },
    ],
    pendingSessions: [],
    walletChallenges: [],
    properties: [
      {
        _id: "prop-mountain-villa",
        tokenId: "1001",
        title: "Mountain View Villa",
        location: "Babesa, Thimphu",
        threeWordLocation: "ridge.valley.shares",
        propertyType: "Residential",
        price: "Nu. 85,00,000",
        ownerWallet: seedWallets.sellerA,
        docHash: propertyOneHash,
        documentHash: propertyOneHash,
        docStorageRef: "seed://mountain-view-villa-documents",
        totalSupply: SHARES_PER_PROPERTY,
        status: "LISTED",
        submittedAt,
        approvedAt,
        updatedAt: approvedAt,
        description: "A verified residential villa tokenized into 10,000 ERC-6909 property shares.",
      },
      {
        _id: "prop-commercial-office",
        tokenId: "1002",
        title: "Commercial Office Space",
        location: "Norzin Lam, Thimphu",
        threeWordLocation: "market.office.title",
        propertyType: "Commercial",
        price: "Nu. 65,00,000",
        ownerWallet: seedWallets.sellerA,
        docHash: propertyTwoHash,
        documentHash: propertyTwoHash,
        docStorageRef: "seed://commercial-office-documents",
        totalSupply: SHARES_PER_PROPERTY,
        status: "LISTED",
        submittedAt,
        approvedAt,
        updatedAt: approvedAt,
        description: "Central commercial property available as a full 10,000-share listing.",
      },
      {
        _id: "prop-prime-land",
        tokenId: "1003",
        title: "Prime Land Parcel",
        location: "Taba, Thimphu",
        threeWordLocation: "parcel.slope.registry",
        propertyType: "Land",
        price: "Nu. 28,00,000",
        ownerWallet: seedWallets.sellerB,
        docHash: propertyThreeHash,
        documentHash: propertyThreeHash,
        docStorageRef: "seed://prime-land-documents",
        totalSupply: SHARES_PER_PROPERTY,
        status: "LISTED",
        submittedAt,
        approvedAt,
        updatedAt: approvedAt,
        description: "A verified land parcel with partial shares listed by the original owner.",
      },
    ],
    listings: [
      {
        id: "LST-1001",
        tokenId: "1001",
        sharesForSale: 2500,
        originalShares: 2500,
        pricePerShare: 850,
        sellerWallet: seedWallets.sellerA,
        listingType: "PARTIAL",
        status: "ACTIVE",
        createdAt: "2026-01-20T08:00:00.000Z",
      },
      {
        id: "LST-1002",
        tokenId: "1002",
        sharesForSale: 10000,
        originalShares: 10000,
        pricePerShare: 650,
        sellerWallet: seedWallets.sellerA,
        listingType: "FULL",
        status: "ACTIVE",
        createdAt: "2026-01-21T08:00:00.000Z",
      },
      {
        id: "LST-1003",
        tokenId: "1001",
        sharesForSale: 300,
        originalShares: 300,
        pricePerShare: 910,
        sellerWallet: seedWallets.buyer,
        listingType: "SECONDARY",
        status: "ACTIVE",
        createdAt: "2026-01-22T08:00:00.000Z",
      },
      {
        id: "LST-1004",
        tokenId: "1003",
        sharesForSale: 4000,
        originalShares: 4000,
        pricePerShare: 280,
        sellerWallet: seedWallets.sellerB,
        listingType: "PARTIAL",
        status: "ACTIVE",
        createdAt: "2026-01-23T08:00:00.000Z",
      },
    ],
    balances: {
      [seedWallets.sellerA]: { "1001": 7000, "1002": 10000 },
      [seedWallets.sellerB]: { "1001": 2500, "1003": 10000 },
      [seedWallets.buyer]: { "1001": 500 },
    },
    approvals: [
      { ownerWallet: seedWallets.sellerA, spender: "marketplace", tokenId: "1001", amount: 2500 },
      { ownerWallet: seedWallets.sellerA, spender: "marketplace", tokenId: "1002", amount: 10000 },
      { ownerWallet: seedWallets.buyer, spender: "marketplace", tokenId: "1001", amount: 300 },
      { ownerWallet: seedWallets.sellerB, spender: "marketplace", tokenId: "1003", amount: 4000 },
    ],
    orders: [],
    leases: [],
    transferEvents: [
      {
        id: "EVT-MINT-1001",
        tokenId: "1001",
        fromWallet: ZERO_WALLET,
        toWallet: seedWallets.sellerA,
        qty: 10000,
        txHash: randomHex(32),
        timestamp: approvedAt,
      },
      {
        id: "EVT-SEED-1001-A",
        tokenId: "1001",
        fromWallet: seedWallets.sellerA,
        toWallet: seedWallets.sellerB,
        qty: 2500,
        txHash: randomHex(32),
        timestamp: "2026-02-01T08:00:00.000Z",
      },
      {
        id: "EVT-SEED-1001-B",
        tokenId: "1001",
        fromWallet: seedWallets.sellerA,
        toWallet: seedWallets.buyer,
        qty: 500,
        txHash: randomHex(32),
        timestamp: "2026-02-05T08:00:00.000Z",
      },
      {
        id: "EVT-MINT-1002",
        tokenId: "1002",
        fromWallet: ZERO_WALLET,
        toWallet: seedWallets.sellerA,
        qty: 10000,
        txHash: randomHex(32),
        timestamp: approvedAt,
      },
      {
        id: "EVT-MINT-1003",
        tokenId: "1003",
        fromWallet: ZERO_WALLET,
        toWallet: seedWallets.sellerB,
        qty: 10000,
        txHash: randomHex(32),
        timestamp: approvedAt,
      },
    ],
    auditLog: [
      {
        id: "AUD-SEED-1",
        actor: ADMIN_WALLET_ADDRESSES[0] || "system",
        action: "PLATFORM_SEEDED",
        target: "demo",
        timestamp: approvedAt,
        metadata: { note: "Local development data seeded" },
      },
    ],
  };
};
